version: '3'
services:
  dev:
    image: node:lts-alpine
    user: 1000:998
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 5173:5173

